version: '3.1'

services:

  db:
    image: cgi/hacsec-mysql:0.0.1
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/tmp/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

  api:
    image: cgi/hacsec-api:0.0.1
    restart: always
    ports:
      - 3000:3000

  redis:
    image: redis
    restart: always  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
