version: '3.1'

services:

  db:
    container_name: acmebank-db
    image: cgi/hacsec-mysql:0.0.1

  redis:
    container_name: acmebank-redis
    image: cgi/hacsec-redis:0.0.1

  api:
    container_name: acmebank-api
    image: cgi/hacsec-api:0.0.1
    depends_on:
      - db
      - redis
    environment:
      BANKAPI_DB_HOSTNAME: db
      BANKAPI_REDIS_HOSTNAME: redis
      BANKAPI_REDIS_PORT: 6379
    ports:
      - 3000:3000

  adminer:
    container_name: acmebank-adminer
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  cdn:
    container_name: acmebank-cdn
    image: cgi/hacsec-cdn:0.0.1
    ports:
      - 3001:80
