version: '3.1'

services:

  db:
    container_name: acmebank-db
    image: cgi/hacsec-mysql:0.0.1
    restart: always

  redis:
    container_name: acmebank-redis
    image: cgi/hacsec-redis:0.0.1
    restart: always

  api:
    container_name: acmebank-api
    image: cgi/hacsec-api:0.0.1
    depends_on:
      - db
      - redis
    environment:
      BANKAPI_DB_HOSTNAME: db
      BANKAPI_REDIS_HOSTNAME: redis
      BANKAPI_REDIS_PORT: 6379
    restart: always

  adminer:
    container_name: acmebank-adminer
    image: cgi/hacsec-adminer:0.0.1
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always

  cdn:
    container_name: acmebank-cdn
    image: cgi/hacsec-cdn:0.0.1
    restart: always

  frontend:
    container_name: acmebank-frontend
    image: cgi/hacsec-frontend:0.0.1
    depends_on:
      - api
      - cdn
    ports:
      - 80:80
    restart: always
