version: '3.1'

services:

  db:
    image: dbuchwald/hacsec-mysql:${APP_VERSION}
    build:
      context: bank-database/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    container_name: acmebank-db
    restart: always

  redis:
    image: dbuchwald/hacsec-redis:${APP_VERSION}
    build:
      context: bank-redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: acmebank-redis
    restart: always

  api:
    image: dbuchwald/hacsec-api:${APP_VERSION}
    build:
      context: bank-api/
      args:
        NODE_VERSION: $NODE_VERSION
    container_name: acmebank-api
    depends_on:
      - db
      - redis
    environment:
      BANKAPI_DB_HOSTNAME: db
      BANKAPI_REDIS_HOSTNAME: redis
      BANKAPI_REDIS_PORT: 6379
    restart: always

  adminer:
    image: dbuchwald/hacsec-adminer:${APP_VERSION}
    build:
      context: bank-adminer/
      args:
        ADMINER_VERSION: $ADMINER_VERSION
    container_name: acmebank-adminer
    depends_on:
      - db
    restart: always

  cdn:
    image: dbuchwald/hacsec-cdn:${APP_VERSION}
    build:
      context: bank-cdn/
      args:
        HTTPD_VERSION: $HTTPD_VERSION
    container_name: acmebank-cdn
    restart: always

  fake-login:
    image: dbuchwald/hacsec-fake-login:${APP_VERSION}
    build:
      context: bank-fake-login/
      args:
        NODE_VERSION: $NODE_VERSION
    container_name: acmebank-fake-login
    ports:
      - 8005:8005
    restart: always

  frontend:
    image: dbuchwald/hacsec-frontend:${APP_VERSION}
    build:
      context: bank-frontend/
      args:
        HTTPD_VERSION: $HTTPD_VERSION
        NODE_VERSION: $NODE_VERSION
    container_name: acmebank-frontend
    depends_on:
      - api
      - cdn
    ports:
      - 80:80
    restart: always
