version: '3.1'

services:

  db:
    image: dbuchwald/hacsec-test-mysql:${TEST_APP_VERSION}
    build:
      context: test-database/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    container_name: test-app-db
    restart: always

  redis:
    image: dbuchwald/hacsec-test-redis:${TEST_APP_VERSION}
    build:
      context: test-redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: test-app-redis
    restart: always

  api:
    image: dbuchwald/hacsec-test-api:${TEST_APP_VERSION}
    build:
      context: test-api/
      args:
        NODE_VERSION: $NODE_VERSION
    container_name: test-app-api
    depends_on:
      - db
      - redis
    environment:
      TESTAPI_DB_HOSTNAME: db
      TESTAPI_REDIS_HOSTNAME: redis
      TESTAPI_REDIS_PORT: 6379
      TESTAPI_HOST_HOSTNAME: ${HOST_HOSTNAME}
    restart: always

  adminer:
    image: dbuchwald/hacsec-test-adminer:${TEST_APP_VERSION}
    build:
      context: test-adminer/
      args:
        ADMINER_VERSION: $ADMINER_VERSION
    container_name: test-app-adminer
    depends_on:
      - db
    restart: always

  cdn:
    image: dbuchwald/hacsec-test-cdn:${TEST_APP_VERSION}
    build:
      context: test-cdn/
      args:
        HTTPD_VERSION: $HTTPD_VERSION
    container_name: test-app-cdn
    restart: always

  frontend:
    image: dbuchwald/hacsec-test-frontend:${TEST_APP_VERSION}
    build:
      context: test-frontend/
      args:
        NODE_VERSION: $NODE_VERSION
        HTTPD_VERSION: $HTTPD_VERSION
    container_name: test-app-frontend
    depends_on:
      - api
      - cdn
    ports:
      - 80:80
    restart: always
